export const CONFIG = {
  // Pagination
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
  MAX_LIMIT: 100,

  // Chat
  MAX_MESSAGE_LENGTH: 2000,
  MAX_CHAT_HISTORY: 5,
  MAX_MEDICAL_NOTES_CONTEXT: 500,

  // AI
  GEMINI_MAX_OUTPUT_TOKENS: 2048,
  GEMINI_TEMPERATURE: 0.7,

  // Rate limiting
  RATE_LIMIT_WINDOW_MS: 15 * 60 * 1000, // 15 minutes
  RATE_LIMIT_MAX_REQUESTS: 100,
  RATE_LIMIT_AUTH_MAX: 5,
  RATE_LIMIT_CHAT_MAX: 20,
} as const;
